// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     *int       `json:"id,omitempty"`
	User   *User      `json:"user"`
	Postid int        `json:"postid"`
	Text   string     `json:"text"`
	Answer []*Comment `json:"answer,omitempty"`
}

type CreateCommentInput struct {
	ID   *int   `json:"id,omitempty"`
	Text string `json:"text"`
}

type CreatePostInput struct {
	ID         *int    `json:"id,omitempty"`
	Title      string  `json:"title"`
	Text       *string `json:"text,omitempty"`
	Commenting bool    `json:"commenting"`
}

type CreateUserInput struct {
	ID       *int   `json:"id,omitempty"`
	Username string `json:"username"`
}

type Mutation struct {
}

type Post struct {
	ID         *int       `json:"id,omitempty"`
	User       *User      `json:"user"`
	Title      string     `json:"title"`
	Text       *string    `json:"text,omitempty"`
	Commenting bool       `json:"commenting"`
	Comments   []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       *int       `json:"id,omitempty"`
	Username string     `json:"username"`
	Posts    []*Post    `json:"posts,omitempty"`
	Comments []*Comment `json:"comments,omitempty"`
}
